spring.application.name=CrisisManagementBackend

# SQLite Configuration
spring.datasource.url=jdbc:sqlite:crisis_management.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# File Upload Configuration
file.upload-dir=uploads
spring.servlet.multipart.max-file-size=16MB
spring.servlet.multipart.max-request-size=16MB

# Gemini Configuration
gemini.api.key=YOUR_GEMINI_API_KEY
